apiVersion: v1
kind: Service
metadata:
  name: django-api-service
spec:
  selector:
    app: django-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
      - name: django-api
        image: nickandrew01/projects:django-be-0.1.0
        ports:
        - containerPort: 8000
          name: web
        resources:
          requests:
            cpu: "100m" # Request 100 millicpu (0.1 CPU)
            memory: "128Mi" # Request 128 Mebibytes of memory
          limits:
            cpu: "200m" # Limit to 200 millicpu (0.2 CPU)
            memory: "256Mi" # Limit to 256 Mebibytes of memory
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
spec:
  rules:
  - host: "django.localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-api-service
            port:
              number: 8000