apiVersion: v1
kind: Service
metadata:
  name: react-web-service
spec:
  selector:
    app: react-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
      - name: react-web
        image: react-fe:2.1.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m" # Request 100 millicpu (0.1 CPU)
            memory: "128Mi" # Request 128 Mebibytes of memory
          limits:
            cpu: "200m" # Limit to 200 millicpu (0.2 CPU)
            memory: "256Mi" # Limit to 256 Mebibytes of memory
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-ingress
spec:
  rules:
  - host: "react.localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-web-service
            port:
              number: 80