# Generated by Django 5.0.3 on 2024-03-27 20:50

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Bob Silver", email="joe@email.com", document="22342342", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
