name: React Docker Test+Build+Push

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'terraform/*'
      - 'helm/*'
      - 'k8s/*'
      - 'django_react_proj/*'
      - '.github/workflows/django.yml*'
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - 'terraform/*'
      - 'helm/*'
      - 'k8s/*'
      - 'django_react_proj/*'
      - '.github/workflows/django.yml*'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Set debug mode for actions steps
    strategy:
      matrix:
        node-version: [ 18 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          student-fe
    - name: Test Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: student-fe/package-lock.json
    - run: |
        pwd &&
        cd ./student-fe &&
        pwd &&
        npm --version
        sudo npm config set registry http://registry.npmjs.org
        sudo npm ci &&
        sudo npm run build --if-present &&
        sudo npm test
  build:
    needs: test
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          student-fe
    # - name: Set up QEMU # Add support for more platforms with QEMU (optional)
    #   uses: docker/setup-qemu-action@v3  # https://github.com/docker/setup-qemu-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:student-fe"
        push: true
        tags: nickandrew01/projects:react-fe-0.1.0